name: Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: sbp_0b9414bd4b646fe86f1e657ffe72b65a7fb448af
      PROJECT_ID: aakbcwmokrispvbkgwjf

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: |
          supabase functions deploy ping --project-ref $PROJECT_ID --no-verify-jwt
          supabase functions deploy discolike-api --project-ref $PROJECT_ID --no-verify-jwt
          supabase functions deploy forward-to-webhook --project-ref $PROJECT_ID --no-verify-jwt
          supabase functions deploy coupons --project-ref $PROJECT_ID --no-verify-jwt
          supabase functions deploy generate-api-key --project-ref $PROJECT_ID --no-verify-jwt
          supabase functions deploy stripe --project-ref $PROJECT_ID --no-verify-jwt
