name: Deploy Function

on:
  push:
    branches:
      - production
      - beta
      - dev-ayush
      - deg-griffin
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: sbp_0b9414bd4b646fe86f1e657ffe72b65a7fb448af
      PROJECT_ID: aakbcwmokrispvbkgwjf

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy ping --project-ref $PROJECT_ID




# SUPABASE_ACCESS_TOKEN: secrets.SUPABASE_ACCESS_TOKEN 